title: Aneerban Chowdhury
logo: "/profile.png?raw=true"
description: > 
 Aspiring Software Engineer
  <br><br>
  <a href="mailto:aneerban10@gmail.com">aneerban10@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/aneerban-chowdhury/">LinkedIn Profile</a>
  <br><br>
theme: jekyll-theme-minimal
